### ISSUE TITLE
Warning when using "vim" for groups of covariates

### ISSUE THREAD

**Issue by mizano924** [bdwilliamson/vimpy#2] opened 2018-02-21 21:17 UTC
Hello - I am trying to use your package for an analysis. I loaded the "Boston" dataset and tried running the "vim" function for groups of covariates. I get the following warning:

**> neigh.vim <- vim(full.fit, fit ~ x, data = Boston3, y = Boston3$medv,
+                  s = c(1, 2, 3, 4, 10, 11, 12, 13), SL.library = learners.2)
Warning messages:
1: In if (standardized) { :
  the condition has length > 1 and only the first element will be used
2: In if (standardized) { :
  the condition has length > 1 and only the first element will be used
3: In if (standardized) { :
  the condition has length > 1 and only the first element will be used**

Would appreciate your advice on whether this is something to worry about.

Best,

**Comment by bdwilliamson** [comment] 2018-02-21 21:49
Hi there! I'm glad you're using the package. I have a couple of questions for you:

(1) Are you using the R package or the Python package (you're currently on the page for the Python package, but your code chunk and warnings look like R to me)?

(2) Which version of the package are you using? Regardless, I have fixed some printing errors in the most recent version of the package (version 0.0.3, updated today), so please install that version!

(3) Were you trying to run the code in the vignette? If so, then there was an argument mismatch in a recent version---I updated the argument "s" in vim() to be "indx" instead, to solve some confusion on my end, but I didn't port that change over to the vignette. I suspect that if you re-run the code in the vignette after downloading the most recent version of the package, things should be fixed.

Happy analyzing!
Brian

**Comment by mizano924** [comment] 2018-02-21 21:57
Hi Brian -

Thanks for the quick reply. The answers to your questions are as follows:
1) I am using the R package - apologies for the confusion.

2) I re-installed the package earlier today. I will re-install and rerun.

3) Yes, I was running the code from the vignette. I must have looked at it before it was updated. 

I have one last question:

If I define a variable as a factor, will it be analyzed as a categorical covariate? 

Thanks again.

**Comment by bdwilliamson** [comment] 2018-02-21 22:12
Great, thanks for your answers---I think that the fixes I applied in the update should get everything working for you.

The covariates are all analyzed by my algorithm the same, by first including them in the regression analysis and then not including them. With that said, if you specify individual learners in your library that handle categorical covariates (or factors), then the variable will be analyzed as a categorical covariate. Does that answer your question?

**Comment by mizano924** [comment] 2018-02-21 22:22
Yes, thank you very much!

**Comment by bdwilliamson** [comment] 2018-02-21 22:30
I'm glad that helped! I'm going to mark this issue as closed, but definitely reach out again if you run into problems that you think are caused by my code!

Thanks again for using the package, and I hope that you get interesting results!

**Closed by bdwilliamson** 2018-02-21 22:30 UTC
